repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev:  v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_trivy
      - id: terraform_checkov
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
