rm-path: "/Users/joshuavink/Devoteam/speech-to-text/cloud_foundations/resource-manager"
iam-path: "/Users/joshuavink/Devoteam/speech-to-text/cloud_foundations/iam"
modules-path: "/Users/joshuavink/Devoteam/speech-to-text/cloud_foundations/modules"

folder-namespace: "fo"
project-namespace: "pj"
service-account-namespace: "sa"
